DELETE FROM `ca_basket` WHERE 1;
ALTER TABLE `ca_basket` AUTO_INCREMENT=1;
DELETE FROM `ca_buyers` WHERE 1;
ALTER TABLE `ca_buyers` AUTO_INCREMENT=1;
DELETE FROM `ca_invoices` WHERE 1;
ALTER TABLE `ca_invoices` AUTO_INCREMENT=1;
